'use client'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterProvider from '@/providers/ToasterProvider'
import { useSession, SessionProvider } from 'next-auth/react'

// export const metadata: Metadata = {
//   title: 'test1',
//   description: 'Generated by create next app',
// }

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  const {data: session } = useSession()
  if (!session) {
    return null
  }
 else {return (
    <html lang="en">
      <body>
        <ToasterProvider />
        {children}
        </body>
    </html>
  )}
}

const RootLayoutProvider = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionProvider session={undefined}>
      {/* Replace `undefined` with your session data if needed */}
      <RootLayout>{children}</RootLayout>
    </SessionProvider>
  )
}

export default RootLayoutProvider