'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterProvider from '@/providers/ToasterProvider'
import { useSession } from 'next-auth/react'

export const metadata: Metadata = {
  title: 'test1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        {children}
        </body>
    </html>
  )
}
