'use client'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterProvider from '@/providers/ToasterProvider'
import { useSession, SessionProvider } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { redirect } from 'next/dist/server/api-utils'
import AuthForm from './(components)/auth/page'

// export const metadata: Metadata = {
//   title: 'test1',
//   description: 'Generated by create next app',
// }

const RootLayout =  ({
  children,
}: {
  children: React.ReactNode
}) => {
  const {data: session } = useSession()
  const router = useRouter()
  if (!session) {
    router.push('/auth')
    return null
  }
 else {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        {children}
        </body>
    </html>
  )}
}

const RootLayoutProvider = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionProvider>
      {/* Replace `undefined` with your session data if needed */}
      <RootLayout>
        <AuthForm />
        {children}
        </RootLayout>
    </SessionProvider>
  )
}

export default RootLayoutProvider