import type { Metadata } from "next";
import Head from "next/head";


type Dashboard = {
    children: React.ReactNode
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}, ) {
  return (
    <html lang="en">
      <body className=''>
        {/* <Head></Head> */}
        {children}
      </body>
    </html>
  );
}
